[package]
name = "frodo"
version = "0.1.0"
edition = "2021"
license = "MIT"
keyword = ["music","smf","midi"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
